version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: resume_analyzer_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-resume_analyzer}
      MYSQL_USER: ${DB_USER:-appuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-apppassword}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  # Resume Screener Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_analyzer_app
    restart: unless-stopped
    ports:
      - "${PORT:-8501}:8501"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER:-appuser}
      - DB_PASSWORD=${DB_PASSWORD:-apppassword}
      - DB_NAME=${DB_NAME:-resume_analyzer}
      - APP_ENV=${APP_ENV:-development}
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
